package com.ogsedas.openmovies.model

import androidx.compose.ui.graphics.Color

data class Movie(
    val id: String,
    val title: String,
    val genre: String,
    val rating: Double,
    val duration: String,
    val certificate: String,
    val format: String,
    val synopsis: String,
    val showtimes: List<String>,
    val primaryColor: Color,
    val secondaryColor: Color
)

object SampleMovies {
    val list = listOf(
        Movie(
            id = "m1",
            title = "Interstellar Odyssey",
            genre = "Sci-Fi / Adventure",
            rating = 8.9,
            duration = "2h 45m",
            certificate = "PG-13",
            format = "IMAX Laser",
            synopsis = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
            showtimes = listOf("15:30", "18:45", "21:30"),
            primaryColor = Color(0xFF1E3A8A),
            secondaryColor = Color(0xFF06B6D4)
        ),
        Movie(
            id = "m2",
            title = "Shadows in the Mist",
            genre = "Neo-Noir / Thriller",
            rating = 8.4,
            duration = "2h 10m",
            certificate = "R",
            format = "Dolby Cinema",
            synopsis = "A relentless detective uncovers a labyrinth of corruption spanning the highest levels of the city.",
            showtimes = listOf("16:00", "19:15", "22:00"),
            primaryColor = Color(0xFF4C1D95),
            secondaryColor = Color(0xFFF43F5E)
        ),
        Movie(
            id = "m3",
            title = "Chronicles of Dune",
            genre = "Epic / Fantasy",
            rating = 8.7,
            duration = "2h 38m",
            certificate = "PG-13",
            format = "IMAX 70mm",
            synopsis = "A mythic and emotionally charged hero's journey amidst the dangerous desert planet of Arrakis.",
            showtimes = listOf("14:45", "17:50", "21:00"),
            primaryColor = Color(0xFFB45309),
            secondaryColor = Color(0xFFF59E0B)
        ),
        Movie(
            id = "m4",
            title = "Neon Velocity",
            genre = "Cyber Action",
            rating = 8.1,
            duration = "1h 55m",
            certificate = "PG-13",
            format = "4DX Extreme",
            synopsis = "In a neon-drenched metropolis, underground racers race through forbidden transit arteries.",
            showtimes = listOf("17:00", "19:40", "22:20"),
            primaryColor = Color(0xFF0F766E),
            secondaryColor = Color(0xFF10B981)
        ),
        Movie(
            id = "m5",
            title = "The Silent Echo",
            genre = "Psychological Drama",
            rating = 8.5,
            duration = "2h 05m",
            certificate = "R",
            format = "Laser 4K",
            synopsis = "A renowned sound designer begins hearing frequencies that appear to communicate from the future.",
            showtimes = listOf("16:30", "19:00", "21:45"),
            primaryColor = Color(0xFF374151),
            secondaryColor = Color(0xFF9CA3AF)
        ),
        Movie(
            id = "m6",
            title = "Solaris Protocol",
            genre = "Space Thriller",
            rating = 8.6,
            duration = "2h 20m",
            certificate = "PG-13",
            format = "IMAX 3D",
            synopsis = "Scientists stationed on an orbital station investigate mysterious emotional anomalies generated by a living star.",
            showtimes = listOf("15:00", "18:15", "21:15"),
            primaryColor = Color(0xFF831843),
            secondaryColor = Color(0xFFFB7185)
        )
    )
}
